
---
title: "Project Code"
author: 'Group 2 '
date: "3/14/2021"
output: 

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Libraries}
library(tidyverse)
library(ipumsr)
library(lubridate)
library(vtable)
library(haven)
library(dplyr)
library(estimatr)
library(car)
library(jtools)
library(scales)
library(stringr)
library(ggplot2)
library(Hmisc)


```


```{r Load source code}

##Lynna's Code 
source("/Users/lynnatran/Documents/MSBA/5300 - Econometrics/Data Translation Challenge/Git Repository/Group2DataTranslationChallenge5300/code/Lynna-2RCodeforEmploymentVariables.R")
```


```{r Lala Load source code}
##Lala's Code 
source("/Users/lynnatran/Documents/MSBA/5300 - Econometrics/Data Translation Challenge/Git Repository/Group2DataTranslationChallenge5300/code/03_g2_dtc_tidy_data.R")
```


```{r Rosalie Load source code}
##Rosalie's Code 
source("/Users/lynnatran/Documents/MSBA/5300 - Econometrics/Data Translation Challenge/Git Repository/Group2DataTranslationChallenge5300/code/Yeehaw.R")

```


```{r Vish Load source code}
##Vish's Code 
source("/Users/lynnatran/Documents/MSBA/5300 - Econometrics/Data Translation Challenge/Git Repository/Group2DataTranslationChallenge5300/code/Vishcode.R")
```


```{r Adding primary keys to datasets}
employment_df$household_personid <- paste(employment_df$YEAR, employment_df$MONTH, employment_df$SERIAL, employment_df$PERNUM, sep="-")


displ_workers$household_personid <- paste(displ_workers$year, displ_workers$month, displ_workers$serial, displ_workers$pernum, sep="-")

covid_score$household_personid <- paste(covid_score$year, covid_score$month, covid_score$serial, covid_score$pernum, sep="-")


df$household_personid <- paste(df$year, df$month, df$serial, df$pernum, sep="-")

```


```{r joining datasets }

employment_displaced_df <- employment_df %>%
  full_join(displ_workers, by = 'household_personid')


vtable(employment_displaced_df)

```


```{r group by month to get a Retail Employment monthly statistic}

month_group_df <- employment_displaced_df %>%
  filter(year >= 2018) %>%
  select(YEAR, MONTH, employed, retail, indname) %>%
  mutate(employed_binary = ifelse(employed == TRUE, 1, 0)) %>%
  mutate(retail_noNA = ifelse(is.na(retail) | retail == FALSE, FALSE, TRUE)) %>%
  mutate(retail_binary = ifelse(retail_noNA == TRUE, 1, 0)) %>%
  mutate(retail_employed = employed_binary == 1 & retail_binary == 1) %>%
  mutate(retail_employed_binary = ifelse(retail_employed == TRUE, 1, 0))
  

month_group_df$yearmo <- paste(month_group_df$YEAR, month_group_df$MONTH, sep="-")


month_group_count <- month_group_df %>%
count(YEAR, MONTH, yearmo)


month_group_df <- month_group_df %>%
  select(YEAR, MONTH, yearmo, employed, retail, employed_binary, retail_binary, retail_employed_binary) %>%
  group_by(YEAR, MONTH, yearmo) %>% 
  summarise(Employment = sum(employed_binary), Retail = sum(retail_binary),  RetailEmployed = sum(retail_employed_binary)) %>%
  mutate(afterCovid = (yearmo > '2020-3' | yearmo >= '2020-10')) %>%
  ##month_group_count %>%
  left_join(month_group_count, by =  'yearmo')## %>%
 ## summarise(Retail = sum((retail_binary)))
  ##still need an percentage in retail)

month_group_stats <- month_group_df %>%
 ## left_join(month_group_df, by =  'yearmo') %>%
  filter(yearmo != 'NA-NA') %>%
  mutate(employment_rate = (Employment / n)*100 ) %>%
  ##mutate(retailemployment_rate = ((Retail/Employment)*employment_rate)) %>%
  ##otherindustryemployement_rate
  mutate(retail_rate = (Retail/n) *100) %>%
  mutate(retailemployment_rate = (RetailEmployed/n) *100) 
  
#   
##will need to check if its only employed people with retail jobs  
```


```{r plotting month_group stats pressure, echo=FALSE  }
ggplot(data = month_group_stats, aes( x= yearmo, y = retailemployment_rate )) + geom_point()

```



```{r Employment Regression - Before COVID }


BeforeCovid_monthgroup <- month_group_df %>%
  filter(yearmo < '2020-3') %>%
  filter(yearmo != '2020-10' & yearmo != '2020-11' & yearmo != '2020-12') %>%
  filter(yearmo != 'NA-NA')


BeforeCovid_Employmentregression <- lm(RetailEmployed ~ Employment, 
                                   data = BeforeCovid_monthgroup)

summary(BeforeCovid_Employmentregression)

ggplot(data = BeforeCovid_Employmentregression, aes( x= RetailEmployed, y = Employment)) + geom_point() + geom_smooth()


##plot_coefs(employment_regression)

##histogram

hist(rstandard(BeforeCovid_Employmentregression), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of ')


```


```{r Employment Regression - After COVID }


AfterCovid_monthgroup <- month_group_df %>%
  filter( yearmo >'2020-10' ) %>%
  filter(yearmo != '2020-3' & yearmo != '2020-1' & yearmo != '2020-2'   ) %>%
  filter(yearmo != 'NA-NA')


AfterCovid_Employmentregression <- lm(RetailEmployed ~ Employment, 
                                   data = AfterCovid_monthgroup)

summary(AfterCovid_Employmentregression)

ggplot(data = AfterCovid_Employmentregression, aes( x= RetailEmployed, y = Employment)) + geom_point() + geom_smooth()


hist(rstandard(AfterCovid_Employmentregression), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of ')

```



```{r group by month to get a otherindustry monthly statistic}

otherindustries_df <- employment_displaced_df %>%
  filter(year >= 2018) %>%
  filter(!is.na(indname)) %>%
  select(YEAR, MONTH, employed, indname) %>%
  mutate(employed_binary = ifelse(employed == TRUE, 1, 0)) %>%
  mutate(artind = ifelse(employed_binary == 1 & indname == "Arts, Entertainment, and Recreation, and Accommodation and Food Services", 1,0))%>%
  mutate(constructionind = ifelse(employed_binary == 1 & indname == "Construction", 1,0)) %>%
  mutate(eduind = ifelse(employed_binary == 1 & indname == "Educational Services, and Health Care and Social Assistance", 1,0)) %>%
  mutate(financeind = ifelse(employed_binary == 1 & indname == "Finance and Insurance, and Real Estate and Rental and Leasing", 1,0)) %>%
  mutate(infoind =  ifelse(employed_binary == 1 & indname == "Information", 1,0)) %>%
  mutate(mfind =ifelse(employed_binary == 1 & indname == "Manufacturing", 1,0)) %>%
  mutate(militaryind = ifelse(indname == "Military", 1,0)) %>%
  mutate(otherind = ifelse(employed_binary == 1 & indname == "Other Services, Except Public Administration", 1,0)) %>%
  mutate(proind =  ifelse(employed_binary == 1 & indname == "Professional, Scientific, and Management, and Administrative and Waste Management Services", 1,0)) %>%
  mutate(publicind =  ifelse(employed_binary == 1 & indname == "Public Administration", 1,0)) %>%
  mutate(retailind = ifelse(employed_binary == 1 & indname == "Retail Trade", 1,0)) %>%
  mutate(transportind = ifelse(employed_binary == 1 & indname == "Transportation and Warehousing, and Utilities", 1,0)) %>%
  mutate(wsind = ifelse(employed_binary == 1 & indname == "Wholesale Trade", 1,0))

otherindustries_df$yearmo <- paste(otherindustries_df$YEAR, otherindustries_df $MONTH, sep="-")

  otherindustries_count <- otherindustries_df %>%
count(indname)

otherindustries_df <- otherindustries_df %>%
  group_by(YEAR, MONTH, yearmo) %>%
  summarise(Employment = sum(employed_binary),
            art_count = sum(artind),
            construction_count = sum(constructionind),
            edu_count = sum(eduind),
            finance_count = sum(financeind),
            info_count = sum(infoind),
            military_count = sum(militaryind),
            other_count = sum(otherind),
            pro_count = sum(proind),
            public_count = sum(publicind),
            retail_count = sum(retailind),
            transport_count = sum(transportind),
            ws_count = sum(wsind)
          )


otherindustries_df_stats <- otherindustries_df %>%
  left_join(month_group_count, by =  'yearmo') %>%
  mutate(employment_rate = (Employment / n)*100 ) %>%
  mutate(art_rate = (art_count / n)*100 ) %>%
  mutate(construction_rate = (construction_count / n)*100 ) %>%
  mutate(edu_rate = (edu_count / n)*100 ) %>%
  mutate(finance_rate = (finance_count / n)*100 ) %>%
  mutate(info_rate = (info_count / n)*100 ) %>%
  mutate(military_rate = (military_count / n)*100 ) %>%
  mutate(other_rate = (other_count / n)*100 ) %>%
  mutate(pro_rate = (pro_count / n)*100 ) %>%
  mutate(public_rate = (public_count / n)*100 ) %>%
  mutate(retail_rate = (retail_count / n)*100 ) %>%
  mutate(transport_rate = (transport_count / n)*100 ) %>%
  mutate(ws_rate = (ws_count / n)*100 ) %>%
  mutate(afterCovid = (yearmo > '2020-3' | yearmo >= '2020-10')) %>%
  filter(yearmo != 'NA-NA')


```


```{r plotting other industries}
 
ggplot(data = otherindustries_df_stats, aes( x = yearmo)) +
                                      geom_point(aes(y = art_rate), color = "darkred") +
                                      geom_point(aes(y = construction_rate), color = "red") +
                                      geom_point(aes(y = edu_rate), color = "pink") +
                                      geom_point(aes(y = finance_rate), color = "orange") +
                                      geom_point(aes(y = info_rate), color = "yellow") +
                                      geom_point(aes(y = military_rate), color = "green") +
                                      geom_point(aes(y = other_rate), color = "blue") +
                                      geom_point(aes(y = public_rate), color = "purple") +
                                      geom_point(aes(y = retail_rate), color = "brown") +
                                      geom_point(aes(y = transport_rate), color = "blueviolet") +
                                      geom_point(aes(y = ws_rate), color = "gold")
                                    
                                      

```

```{r BeforeCovid Other Industries Regression }
BeforeCovid_otherindustries <- otherindustries_df %>%
  filter(yearmo < '2020-3') %>%
  filter(yearmo != '2020-10' & yearmo != '2020-11' & yearmo != '2020-12') %>%
  filter(yearmo != 'NA-NA')

BeforeCovid_OtherIndRegression <- lm(retail_count ~ art_count + construction_count + edu_count
                                 + finance_count + info_count + military_count + other_count
                                 + pro_count + public_count + transport_count 
                                 + ws_count  + Employment, data = BeforeCovid_otherindustries)

summary(BeforeCovid_OtherIndRegression)

ggplot(data = BeforeCovid_OtherIndRegression, aes( x= retail_count, y = Employment)) + geom_point() + geom_smooth()


hist(rstandard(BeforeCovid_OtherIndRegression), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of ')

```
```{r  After Covid Industries Regression }
AfterCovid_otherindustries <- otherindustries_df %>%
  filter( yearmo >'2020-10' ) %>%
  filter(yearmo != '2020-3' & yearmo != '2020-1' & yearmo != '2020-2'   ) %>%
  filter(yearmo != 'NA-NA')


AfterCovid_OtherIndRegression <- lm(retail_count ~ Employment + art_count + construction_count + edu_count
                                 + finance_count + info_count + military_count + other_count
                                 + pro_count + public_count + transport_count 
                                 + ws_count  , data = AfterCovid_otherindustries)

summary(AfterCovid_OtherIndRegression)

ggplot(data = AfterCovid_OtherIndRegression, aes( x= retail_count, y = Employment)) + geom_point() + geom_smooth()

#doesnt work because of nulls 
##hist(rstandard(AfterCovid_OtherIndRegression), 
 ##    xlab = "Standardized residuals", main = 'Standardized Residuals of ')


```

```{r testing selected industries}
AfterCovid_OtherIndSelectedRegression <- lm(retail_count ~ Employment + art_count + construction_count + edu_count
                                 + finance_count + info_count + military_count + other_count
                                   , data = AfterCovid_otherindustries)

summary(AfterCovid_OtherIndSelectedRegression)

ggplot(data = AfterCovid_OtherIndSelectedRegression, aes( x= retail_count, y = Employment)) + geom_point() + geom_smooth()

# hist(rstandard(AfterCovid_OtherIndSelectRegression), 
#    xlab = "Standardized residuals", main = 'Standardized Residuals of ')
```



```{r COVID Data}
##Question 3 : r covid variables – compared to our demographics

##We can answer a question like : Women has been less affected by COVID therefore they should be targets 

covidemployment_df <- employment_displaced_df 

person_covid <- covid_score %>%
  left_join(covidemployment_df, by = 'household_personid' ) %>%
  left_join(df, by = 'household_personid'  )

```




```{r COVID REGRESSION DATA}

covid_regression <- lm(covid_score ~ age + + educ99 + female + employed , data = person_covid)
##take out race since thats not a quantitative value 

summary(covid_regression)

##ggplot(data =covid_regression, aes( x= covid_score, y = employed )) + geom_point()
##ggplot(data = covid_regression, aes( x= covid_score, y = )) + geom_point() + geom_smooth()

##effect_plot(covid_regression, pred = 'covid_score', plot.points = TRUE)
```


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```


